#!/bin/bash

# Request a GPU partition node and access to 1 GPU
#SBATCH -p gpu --gres=gpu:1

# Request 1 CPU core
#SBATCH -n 1

#SBATCH --mem=8G
#SBATCH -t 16:15:00
#SBATCH -o sum2.out

module load python/3.7.4
module load anaconda/

source activate nerf

python run_nerf.py --config config_cit_hi_res.txt > logs/cit_res_output.txt